name: Test pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Setup Miniconda
      uses: conda-incubator/setup-miniconda@v2
      with:
        auto-update-conda: true
        miniforge-variant: Miniforge3
        channels: conda-forge,bioconda,defaults
        activate-environment: tblastx-synteny
        use-mamba: false

    - name: Create and Install Conda Environment
      shell: bash -l {0}
      run: |
        conda create --yes -n tblastx-synteny
        conda activate tblastx-synteny
        conda install -n tblastx-synteny --yes --file requirements.txt

    - name: Run tests
      shell: bash -l {0}
      run: |
        conda activate tblastx-synteny
        ./test/test.py

    - name: Run from different directory
      shell: bash -l {0}
      run: |
        conda activate tblastx-synteny
        cd ../
        ./tblastx-synteny/tblastx-synteny.py \
          -q tblastx-synteny/test/data/PbANKA_MIT_v3.fa \
          -s tblastx-synteny/test/data/Pf3D7_MIT_v3.fa \
          -d out
        ls out/PbANKA_MIT_v3_vs_Pf3D7_MIT_v3.paf
